services:
  radar_app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: radar_app:latest
    container_name: radar_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./files:/var/www/storage/app/public/files
    networks:
      - radar_network

  radar_caddy:
    image: caddy:2.8.4
    container_name: radar_caddy
    ports:
      - '9090:9090'
      - '9091:9091'
      - '80:80'
      - '443:443'
    volumes:
      - radar_caddy_config:/config
      - radar_caddy_data:/data
      - ./Caddyfile-Dev:/etc/caddy/Caddyfile
      - .:/var/www
    restart: unless-stopped
    networks:
      - radar_network

  radar_db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: radar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}    
    ports:
      - "3306:3306"
    volumes:
      - radar_db_data:/var/lib/mysql
    networks:
      - radar_network

  radar_visualization:
    image: wwwthoughtworks/build-your-own-radar:latest
    container_name: radar_visualization
    ports:
      - '8081:80'
    environment:
      - SERVER_NAMES=localhost 127.0.0.1
    volumes:
      - ./files:/opt/build-your-own-radar/files
    restart: unless-stopped
    networks:
      - radar_network

networks:
  radar_network:
    driver: bridge

volumes:
  radar_db_data:
    driver: local
  radar_caddy_config:
    driver: local
  radar_caddy_data:
    driver: local
