services:
  radar_db:
    image: mysql:5.7
    container_name: radar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - radar_db_data:/var/lib/mysql
    networks:
      - radar_network

  radar_visualization:
    image: wwwthoughtworks/build-your-own-radar:latest
    container_name: radar_visualization
    ports:
      - '8081:80'
    environment:
      - SERVER_NAMES=localhost 127.0.0.1
    volumes:
      - ./files:/opt/build-your-own-radar/files
    restart: unless-stopped
    networks:
      - radar_network

networks:
  radar_network:
    driver: bridge

volumes:
  radar_db_data:
    driver: local
